import Head from 'next/head'
import { useContext } from 'react'
import { cartContex } from '../../components/modal'

export default function MyCart() {

  const cartCon = useContext(cartContex)

    return (
    <div>
      <Head>
        <title>MyCart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='text-5xl mb-6'>MyCart</h1>
      </main>

      <div>
        <ul>
          {cartCon.cart.map((data, index)=>{
            return (
            <li className='mb-5'>
              <div>
                {`${index + 1}. Nama: ${data.nama}`}
              </div>
              <div>
                {`Alamat: ${data.alamat}`}
              </div>
              <div>
                {`WalletID: ${data.wallet}`}
              </div>
              <div>
                {`Produk: ${data.produk}`}
              </div>
              <div>
                {`Banyak: ${data.count}`}
              </div>
            </li>)
          })}
        </ul>
      </div>
    </div>
    )
}
