import Head from 'next/head'
import Image from 'next/image'
import {IoLocationSharp} from "react-icons/io5"
import {CgProfile} from "react-icons/cg"
import {IoIosArrowDown, IoMdSearch} from "react-icons/io"
import {GiHamburgerMenu} from "react-icons/gi"
import {BsFillBagFill, BsFillShareFill} from "react-icons/bs"

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Shoes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@900&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@600&display=swap" rel="stylesheet"></link>
      </Head>

      <main className='relative bg-gradient-to-r from-red-900 via-red-500 to-red-900 w-full min-h-screen pb-6'>
        <div className='flex flex-col justify-center sm:flex-row sm:justify-start'>

            {/* Logo */}
          <div className='flex justify-center sm:justify-start'>
            <div className='ml-5 relative w-fit mb-6'>
              <Image src={"/img/shoes.svg"} width={60} height={60} />
              <div className='font-PlayFair absolute top-[58px] -left-2 font-medium text-white whitespace-nowrap'>MY SHOES</div>
            </div>
          </div>

          {/* NavBar */}
          <nav className='text-white flex justify-center items-center sm:grow sm:justify-center sm:gap-7 text-sm sm:text-base'>
              <div className='flex flex-row items-center gap-2 mx-2 cursor-pointer font-Lato'>MENS <IoIosArrowDown/></div> 
              <div className='flex flex-row items-center gap-2 mx-2 cursor-pointer font-Lato'>WOMEN <IoIosArrowDown/></div> 
              <div className='flex flex-row items-center gap-2 mx-2 cursor-pointer font-Lato'>KIDS <IoIosArrowDown/></div> 
              <div className='mx-2 cursor-pointer font-Lato'>COSTUMIZE</div>
          </nav>

          <div className='fixed hidden sm:flex flex-col h-screen right-0 shadow-xl'>
            <GiHamburgerMenu className='bg-neutral-700 p-2 cursor-pointer' size={55} color='#FFFFFF'/>
            <div className='bg-gradient-to-b from-red-500 to-red-900 h-full flex justify-center'>
              <div className='flex flex-col grow'>
                <div className='w-full flex justify-center flex-col items-center'>
                  <BsFillBagFill className='scale-125 my-8 cursor-pointer' color='#FFFFFF'/>
                  <IoLocationSharp className='scale-125 my-8 cursor-pointer' color='#FFFFFF'/>
                  <CgProfile className='scale-125 my-8 cursor-pointer' color='#FFFFFF'/>
                  <IoMdSearch className='scale-125 my-8 cursor-pointer' color='#FFFFFF'/>
                </div>
                <div className='w-full grow flex justify-center items-end'>
                  <BsFillShareFill className='scale-125 my-8 cursor-pointer' color='#FFFFFF'/>
                </div>
              </div>
            </div>
          </div>

        </div>

        {/* Burger Menu */}
          <div className='fixed flex cursor-pointer items-center inset-0 w-16 h-16 sm:hidden'>
            <GiHamburgerMenu className='ml-1' size={55} color='#FFFFFF'/>
          </div>


        {/* Main Content */}
        <div className='flex justify-center flex-col sm:mr-16'>
          <div className='relative text-center md:text-left md:flex md:justify-center'>
            <Image src={"/img/shoes-hero.png"} width={450} height={450}/>
            <div className='hidden md:flex flex-col justify-center'>
              <div className= 'text-white font-Inter font-extrabold text-5xl'>NIKE AIR JORDAN</div>
              <div className= 'text-white'>MEN'S ORIGINAL</div>
              <div className= 'text-white opacity-75 text-5xl'>$120</div>
            </div>
          </div>
          <div className='text-center mx-2 mt-4 md:hidden'>
            <div className= 'text-white font-Inter font-extrabold text-6xl'>NIKE AIR JORDAN</div>
            <div className= 'text-white mt-2'>MEN'S ORIGINAL</div>
            <div className= 'text-white opacity-75'>$120</div>
          </div>

          <div className='flex justify-center mt-6 md:mt-2'>
            <div className='bg-neutral-700 cursor-pointer px-9 py-2 hover:scale-125 rounded-xl font-bold text-slate-200'>BUY NOW</div>
          </div>

        </div>

      </main>

    </div>
  )
}
