import Head from 'next/head'
import { Logo } from '../components/logo'
import { DropDownList, Navbar, NavbarList } from '../components/navbar'
import {BsFillBagFill} from "react-icons/bs"
import {IoLocationSharp} from "react-icons/io5"
import {CgProfile} from "react-icons/cg"
import {IoMdSearch} from "react-icons/io"
import { Sidebar, SidebarList } from '../components/sidebar'
import { Body } from '../components/body'
import { Modal } from '../components/modal'
import { createContext, useState } from 'react'

export const modalContex = createContext()

export default function Home() {

  const [modalShow, setmodalShow] = useState(false)

  return (
    <>

      <Head>
        <title>My Shoes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@900&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@600&display=swap" rel="stylesheet"></link>
      </Head>

      <main className='relative flex flex-col bg-gradient-to-r from-red-900 via-red-500 to-red-900 w-screen min-h-screen pb-6'>
        
        <div id='topBar' className='flex flex-col justify-center sm:flex-row sm:justify-start'>

          <Logo className="flex justify-center sm:justify-start cursor-pointer"/>

          <Navbar>
            <NavbarList isDropdown={true} text="MENS">
              <DropDownList text="a"/>
              <DropDownList text="b"/>
              <DropDownList text="c"/>
            </NavbarList>
            <NavbarList isDropdown={true} text="WOMEN">
              <DropDownList text="a"/>
              <DropDownList text="b"/>
              <DropDownList text="c"/>
            </NavbarList>
            <NavbarList isDropdown={true} text="KIDS">
              <DropDownList text="a"/>
              <DropDownList text="b"/>
              <DropDownList text="c"/>
            </NavbarList>
            <NavbarList isDropdown={false} text="COSTUMIZE"/>
          </Navbar>

          <Sidebar>
            <SidebarList icon={BsFillBagFill}/>
            <SidebarList icon={IoLocationSharp}/>
            <SidebarList icon={CgProfile}/>
            <SidebarList icon={IoMdSearch}/>
          </Sidebar>

        </div>
        
          {/* Main Content */}
          <modalContex.Provider value={{modalShow,setmodalShow}}>
            <Body
            imgSrc = "/img/shoes-hero.png"
            nameProduct= "NIKE AIR JORDAN"
            category = "MEN'S ORIGINAL"
            price = {120}
            />

            <Modal/>
          </modalContex.Provider>

      </main>
    </>
  )
}
