import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Shoes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet"></link>
      </Head>

      <main>
        <div className='bg-gradient-to-b from-red-700 via-red-500 to-red-700 w-screen h-screen'>
          <div className='ml-4 relative w-fit'>
            <Image src={"/img/shoes.svg"} width={60} height={60} />
            <div className='font-PlayFair absolute top-[58px] -left-2 font-medium text-white whitespace-nowrap'>MY SHOES</div>
          </div>
        </div> 
      </main>
    </div>
  )
}
